### ISSUE TITLE
RasPlex not a client

### ISSUE THREAD

**Issue by fourbytes** [samcm/PlexTogether#45]
Not sure if this can be easily fixed or is a larger issue, but rasplex isn't shown as a player even though it should.

**Comment by samcm** [comment]
Where abouts? The warning for Plex Web should only show up if it detects Web within the Platform/Client text.

**Comment by fourbytes** [comment]
Sorry, I mean it doesn't show up at all in the list, but does through the plex web/mobile apps.

**Comment by samcm** [comment]
Are you signed in to the same Plex account on both PlexTogether and the rasplex device?

**Comment by fourbytes** [comment]
Yep

**Comment by fourbytes** [comment]
It shows up under `https://plex.tv/devices.xml`, but not `https://plex.tv/api/resources?includeHttps=1`, not sure what the exact differences are between those endpoints though.

**Comment by samcm** [comment]
Is there an option within the Rasplex settings to advertise as a player? If so, that will be enabled. Just thinking off the top of my head because thats the case with the iOS app.

**Comment by fourbytes** [comment]
Can't find one, but it advertises as a player in both the iOS plex app, and the web app (it shows in both the player menus)

**Comment by samcm** [comment]
Hmm. How long has it been? I've previously used Rasplex successfully and a couple others have as well so I don't think its a platform problem. There is a half decent chance its just something related to the Plex.tv maintenance today and will will eventually fix itself. 

The reason it'll show up in official Plex apps is because they use multiple methods of Client discovery like GDM. We're reliant on just `https://plex.tv/api/resources?includeHttps=1`. I could maybe implement pulling clients from `https://plex.tv/devices.xml` as well if this doesn't fix itself.

**Comment by fourbytes** [comment]
Hmmm, it's been like this since I first used it a couple of days ago, I'll try keep messing with some things and see if I can get it to work.

**Comment by fourbytes** [comment]
It's recently started coming up and works fine now, not sure what was up originally or if plex did something to fix but seems to be sorted.
