### ISSUE TITLE
Using it without User2,.. needing to sign in

### ISSUE THREAD

**Issue by thibaultmol** [samcm/PlexTogether#49]
Hi,

So would it be possible to make an (optional) system where I can just share the plextogether link, and that the receiving users don't have to get a plex account, share my library with, then log into plextogether.

Reason why I'm asking this is because I've been trying to find an easy way to watch plex together with friends in VR (such as AltspaceVR). If I could just put a url on the virtual screen (plextogether link). They wouldn't have to even realize that it's actually plex in the background. 

I don't know if it's possible to do this with the api's. But just wanted to throw it out there :-)

**Comment by Ahsome** [comment]
Nup, because sadly PlexTogether doesn't actually send a video feed to the other users, the other uses need to have a copy of the video/have a shared library with the file

That's why you still need them to make an account so they can link a copy of the video to their account

**Comment by thibaultmol** [comment]
I was afraid that'd be the case.

I wish there was a way to share a video somehow. Like how you can share an MP4 on Google Drive

**Comment by pcjonathan** [comment]
I'd actually love this in some form as it would make group rewatch/discussion sessions so so easier since I don't think people would want to go through the effort of creating a Plex account and logging in and such. In fact, it's been more or less the main reason why I don't use PlexTogether a LOT more.

Could we perhaps have the option of a default token that people can use if they don't supply their own via logging in? Plex provides the option for a guest managed/home account w/ easy turn on/off that would fit absolutely perfectly for this. And we could always use other temp managed accounts or, especially if free, just create a whole new user and use that.

I quickly tested it by swapping out my access token with guest's in Chrome Dev Tools and it seemed to work fine, except for name being reported as Null (although I'd imagine for this general idea to work, a naming thing would need to be sorted out regardless).

**Comment by samcm** [comment]
I've had a look at how plex.tv/web handles a lot of the account/sharing settings and there isn't many cases where `CORS` is enabled. This unfortunately rules out PT from being able to edit these settings. 

Even if we could get it working though, I'm sort of hesitant to do anything like this with PT. Last time I checked users within your Plex home/guest accounts have the same access levels to your servers as the master account. It's just not something I'm comfortable in doing. Sorry. 

As for an 'easier' solution to sharing, I used to just use nginx-rtmp on a vps to setup a basic low latency rtmp stream and would feed a movie in to that. Maybe that would be a viable alternative if not everyone has a Plex account.
